# config/routes.yaml
app_home:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET

app_property:
    path: /property
    controller: App\Controller\HomeController::property
    methods: GET

app_login:
    path: /login
    controller: App\Controller\HomeController::login
    methods: GET

app_register:
    path: /register
    controller: App\Controller\HomeController::register
    methods: GET

app_about:
    path: /about
    controller: App\Controller\HomeController::about
    methods: GET